### ISSUE TITLE
knife-solo always asking for password.

### ISSUE THREAD

**Issue by atomi** [matschaffer/knife-solo#261]
Just wanted to post this here to make sure it's documented.
When I run knife solo prepare or knife solo cook, I get asked for a password - even though it doesn't need it. Knife Solo version 0.2.0 ruby 1.9.3p362 (2012-12-25) [i386-mingw32]

**Comment by wtfiwtz** [comment]
This can happen on Mac OS X with multiple SSH agent keys... 

```
ssh-add -L              # shows multiple identities
ssh-add -D              # delete all identities
ssh-add ~/.ssh/id_rsa   # add the specific identity you need as #1
```
