### ISSUE TITLE
ERROR: TypeError: can't convert Array into String

### ISSUE THREAD

**Issue by daachi** [matschaffer/knife-solo#278]
I've come to rely on knife solo and for months it has worked without issue. Recently I rebuilt my gemset and version 0.3.0 was installed, and now knife solo simply doesn't work. Everything I've tried so far results in this error locally.

When I try to run chef-solo -j dna.json on an instance where the 'kitchen' has been uploaded I get an error message that the cookbooks can't be found.

I've spent about two full days trying to figure out how to get this working and am giving up at this point.

**Comment by tombeynon** [comment]
2 years later - thank you @tmatilai!

**Comment by thomasbiddle** [comment]
Another thanks to @tmatilai ! I ended up using this in `solo.rb` for a chef-solo setup. My only change was that I had to point it at the root folder for what held my environment folder.
