### ISSUE TITLE
Problem with the compatible version of mixlib-shellout gem

### ISSUE THREAD

**Issue by dannysalazar90** [matschaffer/knife-solo#415]
Good day, im having this problem when im trying to execute any command like chef-solo, knife, etc.
Could you help me with this please ?

C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:1638:in `raise_if_
conflicts': Unable to activate ohai-7.6.0, because mixlib-shellout-1.4.0-x86-min
gw32 conflicts with mixlib-shellout (< 3.0, >= 2.0.0.rc.0) (Gem::LoadError)
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:747:i
n `activate'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:781:i
n `block in activate_dependencies'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:767:i
n `each'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:767:i
n `activate_dependencies'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:751:i
n `activate'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:1232:in `gem'
        from C:/Ruby193/bin/knife:22:in `<main>'

**Comment by lamont-granquist** [comment]
Its nothing to do with knife-solo.  We also don't support gem installs into user maintained rubies on windows at all, please use omnibus chef or chef-dk artifacts.

**Comment by matschaffer** [comment]
Thanks for confirmation @lamont-granquist !
