### ISSUE TITLE
Undefined default_attributes when using JSON enviroment

### ISSUE THREAD

**Issue by andre1810** [matschaffer/knife-solo#416]
Hi,
I´ve an environment called "develop" located unter `enviroments/develop.json`.

```
{
  "name": "dev",
  "description": "An environment for development"
}
````

When I want to run a node with this env I´m getting following errors:

```
Unexpected Error:
-----------------
NoMethodError: undefined method `default_attributes' for #<Hash:0x00000002bc89f8>

[2014-12-12T13:28:11+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 1.577574719 seconds
[2014-12-12T13:28:11+01:00] ERROR: undefined method `default_attributes' for #<Hash:0x00000002bc89f8>
[2014-12-12T13:28:12+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
````
Using a ruby file solves the issue:

```
name "dev"
description "An environment for development"
```

How can I get this working with a json env file? Adding "default_attributes" : {} isn´t working.

**Comment by masonleung** [comment]
I ran into the same issue.  If I use `production.rb` instead of `production.json`, I can create the ec2 instance using `knife` without issue.  Below is my the stacktrace if I use json in the `environments` directory

    Generated at 2015-01-03 08:18:19 +0000
    NoMethodError: undefined method `default_attributes' for #<Hash:0x00000002477b40>
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/node.rb:348:in `apply_expansion_attributes'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/node.rb:334:in `expand!'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:356:in `expand_run_list'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:314:in `build_node'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:484:in `do_run'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:199:in `block in run'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:193:in `fork'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:193:in `run'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/application.rb:183:in `run_chef_client'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/application/solo.rb:239:in `block in run_application'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/application/solo.rb:231:in `loop'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/application/solo.rb:231:in `run_application'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/application.rb:66:in `run'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/bin/chef-solo:25:in `<top (required)>'
    /usr/bin/chef-solo:23:in `load'
    /usr/bin/chef-solo:23:in `<main>'

**Comment by masonleung** [comment]
@andre1810  try `knife environment create production` and use the output as the json template.  I got json to work after digging around.  The `default_attributes` must be part of the json and there are other attributes needed.

**Comment by matschaffer** [comment]
Gonna close this out. Feel free to re-open if `knife environment create` doesn't do the trick.
