### ISSUE TITLE
Chef DK knife command does not like solo argument

### ISSUE THREAD

**Issue by janskarvall** [matschaffer/knife-solo#424]
I installed chefdk_0.4.0-1_amd64.deb on a host with Ubuntu 14.04 Desktop as a learning practice.

The I discovered knife-solo here: [Server provisioning with Chef and knife-solo](http://jenssegers.be/blog/55/server-provisioning-with-chef-and-knife-solo). In there the procedure to install knife-solo is told to be:

    > gem install chef
    > gem install knife-solo
    > gem install librarian-chef

As I already had chefdk installed, I took a chance and only did:

    $ sudo gem install knife-solo
    $ gem install librarian-chef

Then I tried to run `knife solo init`:

    $ cd /tmp
    $ mkdir knife-solo-example
    $ cd knife-solo-example
    $ knife solo init .
    FATAL: Cannot find sub command for: 'solo init .'
    :

I had hoped for that the already installed `knife` should somehow have been extended with the solo argument, but that seems not to be the case.

So, I wonder what is the proper way to resolve this?

**Comment by matschaffer** [comment]
From looking at http://stackoverflow.com/a/24197383/69002 it looks like you probably have to run `chef gem install knife-solo`.

I'm guessing chefdk maintains & uses its own gem space separate from what `gem` uses.

**Comment by robbkidd** [comment]
[Confirmed](https://github.com/chef/chef-dk#chef-gem) that Chef DK has its own embedded Ruby and gem space.

**Comment by matschaffer** [comment]
Thanks @robbkidd !

**Comment by janskarvall** [comment]
Thanks a lot!

    janne@asus:~/chef-repo$ chef gem install knife-solo
    Fetching: knife-solo-0.4.2.gem (100%)
    WARNING:  You don't have /home/janne/.chefdk/gem/ruby/2.1.0/bin in your PATH,
    	  gem executables will not run.
    Thanks for installing knife-solo!
    
    If you run into any issues please let us know at:
      https://github.com/matschaffer/knife-solo/issues

    If you are upgrading knife-solo please uninstall any old versions by
    running `gem clean knife-solo` to avoid any errors.

    See http://bit.ly/CHEF-3255 for more information on the knife bug
    that causes this.
    Successfully installed knife-solo-0.4.2
    1 gem installed
    $ knife solo init .
    Creating kitchen...
    Creating knife.rb in kitchen...
    Creating cupboards...
    Setting up Berkshelf...
    $

**Comment by rotelando** [comment]
Thanks buddy, this was really helpful. Spent the whole day trying to figure that out.

**Comment by deckar01** [comment]
This really confused me, because I installed knife-solo and librarian-chef with `gem install ...` and it worked fine. I later installed Chef DK and started getting `FATAL: Cannot find sub command for: 'solo init .'`.

`chef gem install ...` did the trick.

**Comment by matschaffer** [comment]
@deckar01 glad you found it. Wondering if I should invert the order of the lines in the Usage docs at this point. Some stuff (e.g., berkshelf) is getting harder and harder to use outside of chefdk.
