### ISSUE TITLE
knife solo cook on windows (powershell) can't rsync?

### ISSUE THREAD

**Issue by paul42** [matschaffer/knife-solo#427]
I apologize but I can't quite follow the steps that others have posted, I'm trying to run from windows, using powershell and chef dk, I attempt to run
knife solo cook 10.x.x.x etc and get this error:
ERROR: RuntimeError: Failed to launch command ["rsync", "-rL", "--chmod=ugo=rwX", "--rsh=ssh paul42@10.22.251.86 -i C:\\Users\\paul42\\.chef\\knifeey.pem", "--delete-after", "--exclude=revision-deploys", "--exclude=tmp", "--exclude=.git", "--exclude=.hg","--exclude=.svn", "--exclude=.bzr", "/cygdrive/H/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/knife-solo/resources/patch_cookbooks/", ":~/chef-solo/cookbooks-1"]

attempting a 'chef gem install rysnc' does not fix the problem. I'm not running cygwin/winsshd/mysysgit and attempting this on them leads to other problems (not familar with them or how to set them up)

Thanks for your time,
Paul

**Comment by matschaffer** [comment]
You'll need rsync installed which isn't a gem. https://github.com/tknerr/bills-kitchen has a copy that should work though you may want to take @tknerr's [DevPack](http://blog.tknerr.de/blog/2014/10/09/devpack-philosophy-aka-works-on-your-machine/) approach to installation.

**Comment by paul42** [comment]
reporting back to say grabbing a release from Bill's kitchen worked 100%, and I highly recommend 
https://github.com/tknerr/bills-kitchen to any windows users who are not already well versed in ruby setup (it saved me a ton of time) and Torben is super nice and mega-helpful.

**Comment by tknerr** [comment]
Thanks @paul42 and @matschaffer :blush:
