### ISSUE TITLE
Is it possible to make a converge on client?

### ISSUE THREAD

**Issue by janskarvall** [matschaffer/knife-solo#428]
I have a problem running `knife solo cook` when using `recipe[apache2]`, that I need to understand. Therefor I am thinking that it would help to catch the error by rerunning the converge directly on the client - this without knowing (yet) how to debug.

I get:

    ================================================================================
    Recipe Compile Error in /home/user/chef-solo/cookbooks-2/apache2/attributes/default.rb
    ================================================================================
    
    TypeError
    ---------
    no implicit conversion of String into Integer
    
    Cookbook Trace:
    ---------------
      /home/user/chef-solo/cookbooks-2/apache2/attributes/default.rb:148:in `[]'
      /home/user/chef-solo/cookbooks-2/apache2/attributes/default.rb:148:in `from_file'
    
    Relevant File Content:
    ----------------------
    /home/user/chef-solo/cookbooks-2/apache2/attributes/default.rb:

    141:    default['apache']['conf_dir']    = '/etc/apache2'
    142:    default['apache']['cgibin_dir']  = '/usr/lib/cgi-bin'
    143:    default['apache']['icondir']     = '/usr/share/apache2/icons'
    144:    default['apache']['cache_dir']   = '/var/cache/apache2'
    145:    default['apache']['run_dir']     = '/var/run/apache2'
    146:    default['apache']['lock_dir']    = '/var/lock/apache2'
    147:    # this should use COOK-3917 to educate the initscript of the pid location
    148>>   if node['apache']['version'] == '2.4'
    149:      default['apache']['pid_file']    = '/var/run/apache2/apache2.pid'
    150:      default['apache']['docroot_dir'] = '/var/www/html'
    151:    else
    152:      default['apache']['pid_file']    = '/var/run/apache2.pid'
    153:      default['apache']['docroot_dir'] = '/var/www'
    154:    end
    155:    default['apache']['lib_dir']     = '/usr/lib/apache2'
    156:    default['apache']['libexec_dir']  = "#{node['apache']['lib_dir']}/modules"
    157:    default['apache']['default_site_name'] = '000-default'

/home/user/chef-solo/cookbooks-2/apache2/attributes/default.rb contains:

     44 default['apache']['version'] =
     45   case node['platform_family']
     46   when 'debian'
     47     case node['platform']
     48     when 'ubuntu'
     49       node['platform_version'].to_f >= 13.10 ? '2.4' : '2.2'
     50     when 'linuxmint'
     51       node['platform_version'].to_i >= 16 ? '2.4' : '2.2'
     52     when 'debian', 'raspbian'
     53       node['platform_version'].to_f >= 8.0 ? '2.4' : '2.2'
     54     else
     55       '2.4'
     56     end
     57   when 'rhel'
     58     node['platform_version'].to_f >= 7.0 ? '2.4' : '2.2'
     59   when 'fedora'
     60     node['platform_version'].to_f >= 18 ? '2.4' : '2.2'
     61   when 'suse'
     62     case node['platform']
     63     when 'opensuse'
     64       node['platform_version'].to_f >= 13.1 ? '2.4' : '2.2'
     65       # FIXME: when "suse" for SLES
     66     else
     67       '2.4'
     68     end
     69   when 'freebsd'
     70     node['platform_version'].to_f >= 10.0 ? '2.4' : '2.2'
     71   else
     72     '2.4'
     73   end

Running ohai on the client shows:

      "platform": "ubuntu",
      "platform_version": "14.04",
      "platform_family": "debian",

/var/chef/cache/chef-stacktrace.out:

    Generated at 2015-03-08 00:04:41 +0100
    TypeError: no implicit conversion of String into Integer
    /home/user/chef-solo/cookbooks-2/apache2/attributes/default.rb:148:in `[]'
    /home/user/chef-solo/cookbooks-2/apache2/attributes/default.rb:148:in `from_file'
    /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
    /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
    /opt/chef/embedded/apps/chef/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
    /opt/chef/embedded/apps/chef/lib/chef/dsl/include_attribute.rb:31:in `each'
    /opt/chef/embedded/apps/chef/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
    /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:181:in `load_attribute_file'
    /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:170:in `load_attributes_from_cookbook'
    /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:110:in `block in compile_attributes'
    /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:109:in `each'
    /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:109:in `compile_attributes'
    /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:72:in `compile'
    /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:92:in `load'
    /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
    /opt/chef/embedded/apps/chef/lib/chef/client.rb:235:in `setup_run_context'
    /opt/chef/embedded/apps/chef/lib/chef/client.rb:397:in `run'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:245:in `block in interval_run_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `loop'
    /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `interval_run_chef_client'
    /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:224:in `run_application'
    /opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
    /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
    /usr/bin/chef-solo:40:in `load'
    /usr/bin/chef-solo:40:in `<main>'

**Comment by matschaffer** [comment]
My guess is your node definition (or role or that ever else you might be using to set node attributes) is setting the apache version to `2.4` not `"2.4"`.

As for debugging, I've been known to launch pry from chef code (even attributes files). Just make sure pry is installed into the same gem space that the chef-solo program uses on your server then throw this wherever you need to inspect things: `require 'pry'; binding.pry`

**Comment by janskarvall** [comment]
Spot on! Tried to set ['apache']['listen_ports'] for apache in JSON but did it wrong.

Thanks for debugging tips!

**Comment by matschaffer** [comment]
:+1: glad it worked out
