### ISSUE TITLE
Is it possible to use node specific attributes?

### ISSUE THREAD

**Issue by janskarvall** [matschaffer/knife-solo#430]
I have a need to define port numbers for a node, `192.168.0.183`, that differs from other nodes. I have tried to define it in the `nodes/192.168.0.183.json` like this:
 
```
{
  "run_list": [
    "recipe[apache2]",
  ],
  "automatic": {
    "ipaddress": "192.168.0.183"
  },
  "normal": {  
    "apache2": {
      "http-port": 8080,
      "https-port": 8443
    }
  }
}
```

In a recipe, I refer to the attribute like this:

```
node.default['apache2']['http-port'] = 80
node.default['apache2']['https-port'] = 443

firewall_rule 'http/https' do
  protocol :tcp
  ports [ "#{node['apache2']['http-port']}".to_i, "#{node['apache2']['https-port']}".to_i ]
  action :allow
  notifies :enable, 'firewall[ufw]'
end
```

However, this does not work. The ports on the node `192.168.0.183` get the default values `80` and `443`.

Do I have to create a role specific to the `192.168.0.183` node, setting the port values there? That seems a bit awkward to me.

**Comment by matschaffer** [comment]
Pretty sure you need to take out the normal/automatic keys. At least according to https://docs.chef.io/chef_solo.html#attributes the attributes are specified at the top of the chef solo json spec which is how that file gets used during the run.

**Comment by janskarvall** [comment]
Thanks a lot! That was helpful.

The automatic stuff:

```
  "automatic": {
    "ipaddress": "192.168.0.183"
  },
```

was put in the `nodes/192.168.0.183.json` as a result of running `knife solo prepare user@192.168.0.183`, which created the file. I thought `knife solo cook` was dependent on it, but cooking works after having removed that part, so it seems that it is not needed, and maybe, as you mention, the "automatic" key should not even be there. I ran the prepare as guided by [Server provisioning with Chef and knife-solo](http://jenssegers.be/blog/55/server-provisioning-with-chef-and-knife-solo).

The automatic stuff made me also think that the normal key was necessary. 

Now, my `nodes/192.168.0.183.json` contains:

```
{
  "run_list": [
    "recipe[apache2]",
  ],
  "apache2": {
    "http-port": 8080,
    "https-port": 8443
  }
}
```

It works now, and it works equally well if I move the attributes to the top.

And, maybe, a change is needed to `knife solo prepare` - if that is the recommended way to create the node json file.

I still wonder though, looking at [Attribute Precedence](http://docs.chef.io/attributes.html#attribute-precedence), how to specify precedence for node attributes - even if I do not currently need to do it.

**Comment by matschaffer** [comment]
Thanks, I'll dig it up.

I think at this point in the flow there is no precedence, what's in the
node json clobbers everything else iirc.

2015年3月23日月曜日、janskarvall<notifications@github.com>さんは書きました:

> Thanks a lot! That was helpful.
>
> The automatic stuff:
>
>   "automatic": {
>     "ipaddress": "192.168.0.183"
>   },
>
> was put in the nodes/192.168.0.183.json as a result of running knife solo
> prepare user@192.168.0.183
> <javascript:_e(%7B%7D,'cvml','user@192.168.0.183');>, which created the
> file. I thought knife solo cook was dependent on it, but cooking works
> after having removed that part, so it seems that it is not needed, and
> maybe, as you mention, the "automatic" key should not even be there. I ran
> the prepare as guided by Server provisioning with Chef and knife-solo
> <http://jenssegers.be/blog/55/server-provisioning-with-chef-and-knife-solo>
> .
>
> The automatic stuff made me also think that the normal key was necessary.
>
> Now, my nodes/192.168.0.183.json contains:
>
> {
>   "run_list": [
>     "recipe[apache2]",
>   ],
>   "apache2": {
>     "http-port": 8080,
>     "https-port": 8443
>   }
> }
>
> It works now, and it works equally well if I move the attributes to the
> top.
>
> And, maybe, a change is needed to knife solo prepare - if that is the
> recommended way to create the node json file.
>
> I still wonder though, looking at Attribute Precedence
> <http://docs.chef.io/attributes.html#attribute-precedence>, how to
> specify precedence for node attributes - even if I do not currently need to
> do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/430#issuecomment-84645215>
> .
>


-- 

-Mat

about.me/matschaffer

**Comment by matschaffer** [comment]
Right. Looks like the automatic ip setting is there for search purposes from other node runs: https://github.com/matschaffer/knife-solo/pull/360#discussion_r11890796

I suspect chef-solo doesn't actually read it. I'll leave it in, but I would definitely welcome a pull-request that generates the node JSON files with an example attribute of some kind.

**Comment by janskarvall** [comment]
I dont get what you mean by a pull-request.

I have noted that the "kitchen" uploaded to the target node includes stuff pertaining to other nodes. That seemed a bit strange to me, but I have not thought about the consequences. I had expected that only what the target actually needs whould have been uploaded, but of course, the chef is the chef and decides on how things are used or misused.

I am guessing that searching for ipaddresses of other nodes relies on their node json stuff be there with their automatic ipaddresses. Maybe it had been cleaner to tell other nodes what they need as attributes in their own node json file?

Some loose thoughts from a chef newbee....

**Comment by matschaffer** [comment]
That'd be a question for @alexsiri7 who opened https://github.com/matschaffer/knife-solo/pull/360 (a pull request).

Yes, the whole kitchen is uploaded. I'm not sure it'd be feasible to only upload whats actually needed for the run. If nothing else it'd at least be a lot of work to figure it all out I'm sure.

**Comment by alexsiri7** [comment]
Sadly, I don't have access to the original code that used that "attributes" part. I think doing a search only used the automatic attributes (or maybe it was just something that got copied across from chef-server).  We needed the IP in the node file, as we were using names for the nodes and using that IP to connect. 

I guess if it is confusing it can be removed (or moved out of "automatic").

**Comment by janskarvall** [comment]
Some more thoughts on uploading the full kitchen to every node managed with knife solo.

My thinking is that a security breach on a node would allow sensitive information held in the kitchen being misused, and that such a problem is worsened if information for every node can be accessed.

My impression is, looking at [About Nodes](https://docs.chef.io/nodes.html), that in a Chef Server/Client configuration, it is the Chef Client that has the logic to pull down only what it needs. Maybe the Chef Client could be attacked and changed to pull down anything from the Chef Server unless the Chef Server does not have that logic too, enabling it to refuse non needed pulls, or makes no effort to check that the Chef Client have not been tampered with.

In theory, I guess that the logic of the Chef Client could be reused in the knife solo cook function to prune the not needed parts from the kitchen before upload to the target node.

But maybe this is an overkill to do, as I assume that knife solo is used for small scale networks of nodes, likely managed by a single person.

**Comment by matschaffer** [comment]
Yeah, sounds like overkill to me :)

The security concern should be pretty low since information is never copied
back from the node to the workstation.

2015年3月24日火曜日、janskarvall<notifications@github.com>さんは書きました:

> Some more thoughts on uploading the full kitchen to every node managed
> with knife solo.
>
> My thinking is that a security breach on a node would allow sensitive
> information held in the kitchen being misused, and that such a problem is
> worsened if information for every node can be accessed.
>
> My impression is, looking at About Nodes <https://docs.chef.io/nodes.html>,
> that in a Chef Server/Client configuration, it is the Chef Client that has
> the logic to pull down only what it needs. Maybe the Chef Client could be
> attacked and changed to pull down anything from the Chef Server unless the
> Chef Server does not have that logic too, enabling it to refuse non needed
> pulls, or makes no effort to check that the Chef Client have not been
> tampered with.
>
> In theory, I guess that the logic of the Chef Client could be reused in
> the knife solo cook function to prune the not needed parts from the kitchen
> before upload to the target node.
>
> But maybe this is an overkill to do, as I assume that knife solo is used
> for small scale networks of nodes, likely managed by a single person.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/430#issuecomment-85449049>
> .
>


-- 

-Mat

about.me/matschaffer
