### ISSUE TITLE
require': cannot load such file -- win32/process (LoadError)

### ISSUE THREAD

**Issue by ddpdevang** [matschaffer/knife-solo#431]
C:\Users\Devang\Desktop\chef-solo-example>knife solo init
C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:i
n `require': cannot load such file -- win32/process (LoadError)
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.0.1/lib/m
ixlib/shellout/windows.rb:21:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.0.1/lib/m
ixlib/shellout.rb:32:in `<class:ShellOut>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.0.1/lib/m
ixlib/shellout.rb:26:in `<module:Mixlib>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.0.1/lib/m
ixlib/shellout.rb:24:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/mixin/
shell_out.rb:18:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/util/s
elinux.rb:23:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/config
.rb:25:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/applic
ation.rb:22:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/config
_fetcher.rb:1:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/workst
ation_config_loader.rb:19:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/knife.
rb:23:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/applic
ation/knife.rb:18:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_re
quire.rb:54:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/chef-12.1.1/bin/knife:23:in
 `<top (required)>'
        from C:/Ruby200-x64/bin/knife:23:in `load'
        from C:/Ruby200-x64/bin/knife:23:in `<main>'

**Comment by matschaffer** [comment]
Looks like this is actually a chef bug: https://github.com/chef/chef/issues/1535

It has some information on workarounds but it seems like the recommended approach it to use the windows chef-dk instead of a stock ruby distribution.
