### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by damm** [matschaffer/knife-solo#433]
I noticed the other day it's often brittle and breaks when trying to converge 2 nodes at once.  It appears to be related to the vendoring of the cookbooks before uploading; turns into a race condition where one `knife solo cook` will trample the other directories contents.

Usually it leads to both cook's failing; but it would be awesome if I could run knife solo cook on multiple nodes at the same time.

**Comment by matschaffer** [comment]
Sounds like a noble cause. But first step would be to figure out if librarian & berkshelf can support this. If not the parallelization might have to happen at the ruby-layer.

**Comment by damm** [comment]
Well the problem I noticed is kitchen solo uses the same temporary path always (typically in the resolver's directory) so maybe having it use different directories to export the cookbooks to?

**Comment by arr-dev** [comment]
Just got hit with this. 

Maybe the solution is to expose the `knife[:berkshelf_path]` config in CLI options, 
so we can set different vendor dir for each node?

**Comment by matschaffer** [comment]
Random untested thought: does ENV work in the knife.rb?

2015年6月8日月曜日、Nenad<notifications@github.com>さんは書きました:

> Just got hit with this.
>
> Maybe the solution is to expose the knife[:berkshelf_path] config in CLI
> options,
> so we can set different vendor dir for each node?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/433#issuecomment-109929399>
> .
>


-- 

-Mat

about.me/matschaffer

**Comment by arr-dev** [comment]
Hmm.. Probably. I'll try and get back to you.

**Comment by arr-dev** [comment]
Yeah, it does.

So setting `.chef/knife.rb` with this
```rb
knife[:berkshelf_path] = ENV.fetch('BERKSHELF_VENDOR_PATH', "cookbooks")
```
and running knife solo with `BERKSHELF_VENDOR_PATH=cb1 knife solo cook ...`
works just fine.

Maybe add this to the docs?

**Comment by matschaffer** [comment]
Did a wiki for now https://github.com/matschaffer/knife-solo/wiki/Running-on-multiple-hosts-concurrently

Not quite sure where we should factor this into the main readme but if you have a recommendation let me know.

**Comment by arr-dev** [comment]
Yeah, wiki should do. 
Cheers
