### ISSUE TITLE
Update ruby version requirement to match ohai

### ISSUE THREAD

**Issue by mhow2** [matschaffer/knife-solo#442]
Hi,
I got the following on a fresh Ubuntu 14.04.1 :

```
# gem install knife-solo
Building native extensions.  This could take a while...
Fetching: ffi-yajl-2.2.0.gem (100%)
Building native extensions.  This could take a while...
Fetching: ipaddress-0.8.0.gem (100%)
Fetching: wmi-lite-1.0.0.gem (100%)
Fetching: ffi-1.9.9.gem (100%)
Building native extensions.  This could take a while...
Fetching: rake-10.4.2.gem (100%)
Fetching: ohai-8.5.0.gem (100%)
ERROR:  Error installing knife-solo:
	ohai requires Ruby version >= 2.0.0.
```

**Comment by matschaffer** [comment]
More accurately ohai requires ruby 2. I'll leave this open and re-word to changing our own required ruby version with the next release.

You may want to look at using https://downloads.chef.io/chef-dk/ and installing knife-solo via `chef gem install knife-solo`

That should give you a copy of knife-solo that's bound to chef's bundled ruby thereby matching any required versions.

**Comment by mhow2** [comment]
Hi @matschaffer,
Sorry if I haven't been accurate enough and thanks for the suggestion.
(I got here as I was trying to deploy Huginn https://github.com/cantino/huginn/wiki/Deploying-huginn-on-any-server-or-virtualbox-using-chef-solo-and-or-vagrant)

**Comment by matschaffer** [comment]
Cool. I made (an edit)[https://github.com/cantino/huginn/wiki/Deploying-huginn-on-any-server-or-virtualbox-using-chef-solo-and-or-vagrant/_compare/cbe716239b06256b6064a2ef43512dc10167e83c...f031f98b5df1b8b54c9a554b6a9ea7073ecd4fa2] there so hopefully other folks don't also bump into it.

**Comment by matschaffer** [comment]
Actually it occurred to me that it's probably not the best move for us to lock ruby versions.

We're still compatible with older versions of chef so if we lock to ruby > 2, we'll likely lose compatibility with those versions.

Since the instructions you used skip chef installation you ended up hitting this issue when installing our gem. So I've updated those instructions.
