### ISSUE TITLE
ControlPath should be "more unique"

### ISSUE THREAD

**Issue by aried3r** [matschaffer/knife-solo#443]
Currently, `ControlPath` only set to `%h` but according to [this wiki entry](https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing#Manually_Establishing_Multiplexed_Connections) it should try to be as unique as possible.

> Note that the control socket is named "fred@server.example.org:22", or %r@%h:%p, to try to make the name unique. The sockets should be given unique names. The combination %r,  %h and %p stand for the remote user name, the remote host and the remote host's port.

I *think* I ran into problems because I played around a bit and used different users with `knife-solo` on a test setup. The hostname (`%h`) was always the same and I ran into issues.
```
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]
```

Only after using `--ssh-control-master no` which succeeded, did I investigate further and think this might have caused the problem.

**Comment by matschaffer** [comment]
Fair point. Probably should have the user and port in there. Though I've seen cases where the file name gets too long so could be we should just build some sort of a specific-to-knife-solo hash.

Another thing that came to light in all this is that we could probably gain similar efficiency by pre-staging everything to a local tmp and doing a single rsync. Assuming people aren't rsyncing huge swaths of data anyway.

**Comment by matschaffer** [comment]
Going to close this in favor of #448 - while we could include user & port, I worry about the length of the socket name.

Control master is also a somewhat subtle ssh feature which could cause other oddities if people aren't used to it and doing things like switching users, proxying ports, etc, etc.

Pretty sure doing one bulk rsync is doable and should get us similar (or better) speed with less complexity.
