### ISSUE TITLE
Unable to cook node using two user accounts

### ISSUE THREAD

**Issue by rmoriz** [matschaffer/knife-solo#444]
Gave the current master (6f7ae022e3159ceafe96b38f3e92448ef0051668) a try but `knife solo cook <node>` fails:

```shell
...
Vendoring zap (0.8.4) to cookbooks/zap
Uploading the kitchen...
Generating solo config...
Running Chef: sudo chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json
{:config_missing=>true}
[2015-07-09T11:30:01+00:00] WARN: *****************************************
[2015-07-09T11:30:01+00:00] WARN: Did not find config file: /home/rmoriz/chef-solo/solo.rb, using command line options.
[2015-07-09T11:30:01+00:00] WARN: *****************************************
[2015-07-09T11:30:01+00:00] FATAL: Cannot load configuration from /home/rmoriz/chef-solo/dna.json
ERROR: RuntimeError: chef-solo failed. See output above.
```

Switching back to v0.4.2 fixes it…

**Comment by matschaffer** [comment]
Can you provide the full output with '-VV' ?

Could be an issue with the new ssh/rsync control socket stuff.

On Thursday, July 9, 2015, Roland Moriz <notifications@github.com> wrote:

> Gave the current master (6f7ae02
> <https://github.com/matschaffer/knife-solo/commit/6f7ae022e3159ceafe96b38f3e92448ef0051668>)
> a try but knife solo cook <node> fails:
>
> ...
> Vendoring zap (0.8.4) to cookbooks/zap
> Uploading the kitchen...
> Generating solo config...
> Running Chef: sudo chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json
> {:config_missing=>true}
> [2015-07-09T11:30:01+00:00] WARN: *****************************************
> [2015-07-09T11:30:01+00:00] WARN: Did not find config file: /home/rmoriz/chef-solo/solo.rb, using command line options.
> [2015-07-09T11:30:01+00:00] WARN: *****************************************
> [2015-07-09T11:30:01+00:00] FATAL: Cannot load configuration from /home/rmoriz/chef-solo/dna.json
> ERROR: RuntimeError: chef-solo failed. See output above.
>
> Switching back to v0.4.2 fixes it…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/444>.
>


-- 

-Mat

about.me/matschaffer

**Comment by rmoriz** [comment]
closing this, as I cannot reproduce it right now.

**Comment by rmoriz** [comment]
Okay, so here is the problem again including steps to reproduce:

- provision a VM with root access using ssh keys
- call `knife solo bootstrap fqdn.example.com -x root`
- in a sane environment, this will remove root-login, create admins users with sudo rights
- then call `knife solo cook fqdn.example.com` for subsequent converges.

However, instead of syncing and executing to the root's `/root/chef-solo` the following will be executed:

`sudo chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json`
this expands to the user home of the admin user and fails.

**Comment by rmoriz** [comment]
Okay, found the issue.

When I first bootstrapped the machine as ssh user `root` a local rsync/ssh socket was created in `/Users/rmoriz/.chef/knife-solo-sockets` which later was re-used although the changed other username!

This seems like a bug…

**Comment by matschaffer** [comment]
Yeah, in short term I'm thinking we should include the user & port in the
name and maybe sha it to keep length down.

This also feels like more reason the sockets weren't a great idea, but plan
B (packaging locally then a single rsync) will take some re-work.

On Saturday, September 19, 2015, Roland Moriz <notifications@github.com>
wrote:

> Okay, found the issue.
>
> When I first bootstrapped the machine as ssh user root a local rsync/ssh
> socket was created in /Users/rmoriz/.chef/knife-solo-sockets which later
> was re-used although the changed other username!
>
> This seems like a bug…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/444#issuecomment-141537546>
> .
>


-- 

-Mat

matschaffer.com

**Comment by adamvduke** [comment]
Thanks @rmoriz for reporting this. I just ran into it as well. Should the issue name change to reflect the actual problem for easier searching?

For others that find this issue, I added a hard dependency on `0.4.1` for the time being and it seems to be working as expected.

**Comment by matschaffer** [comment]
Happy to use whatever issue name you think suits the issue best. You may
have edit access, if not just let me know and I'll update it.

The control socket was a 0.5 feature so pinning to less than that should be
good.

I'm planning to replace it with a local staging step in 0.6 so be sure to
try that when it's available.

On Monday, 16 November 2015, Adam Duke <notifications@github.com> wrote:

> Thanks @rmoriz <https://github.com/rmoriz> for reporting this. I just ran
> into it as well. Should the issue name change to reflect the actual problem
> for easier searching?
>
> For others that find this issue, I added a hard dependency on 0.4.1 for
> the time being and it seems to be working as expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/444#issuecomment-156866765>
> .
>


-- 

-Mat

matschaffer.com

**Comment by matschaffer** [comment]
Took a stab at a title. @rmoriz to answer your "no" I suspect I was trying to mirror the way ssh_config defines it (`ControlMaster no`). Though granted, not very idomatic for chef configs.
