### ISSUE TITLE
knife solo prepare is failing on debian jessie

### ISSUE THREAD

**Issue by wingfire** [matschaffer/knife-solo#445]
<code>knife solo prepare root@185.21.100.96</code> is running without an error.
<code>knife solo cook root@185.21.100.96</code> is failing with
  ERROR: RuntimeError: Couldn't find Chef >=0.10.4 on 185.21.100.96. Please run `knife solo prepare root@185.21.100.96` to ensure Chef is installed and up to date.

knife solo prepare root@185.21.100.96 -VV full output: http://paste.debian.net/284125/

**Comment by matschaffer** [comment]
Is this a non-x86 host? Seems like that might be how its ending up in the
gem installation method.

Does the chef omnibus installer work on that host?


-Mat

about.me/matschaffer

**Comment by wingfire** [comment]
It's 64bit. Will check the omnibus installer.
<pre>
uname -a
Linux j226341.servers.jiffybox.net 3.18.9-x86_64-jb1 #2 SMP Wed Mar 25 16:07:36 CET 2015 x86_64 GNU/Linux
</pre>

**Comment by tmatilai** [comment]
Omnibus install for jessie is merged into master in #436, but it's not yet released. You can use [these instructions](https://github.com/matschaffer/knife-solo#cutting-edge) if you want to test it. Or just patch your local gem according to that PR.

I'm closing this issue as it's already implemented. Feel free to ask if you have further questions.

**Comment by matschaffer** [comment]
Thanks Teemu! Guess it's high time for a release. Might need to
fix/rollback the control master stuff though.

On Tuesday, July 21, 2015, Teemu Matilainen <notifications@github.com>
wrote:

> Closed #445 <https://github.com/matschaffer/knife-solo/issues/445>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/445#event-360873641>.
>


-- 

-Mat

about.me/matschaffer
