### ISSUE TITLE
rsync command doesn't work in windows with cygwin due to broken ControlMaster support

### ISSUE THREAD

**Issue by xunnanxu** [matschaffer/knife-solo#450]
The rsync part in knife solo works in linux but fails in windows with cygwin. Typical error messages are:

> mm_receive_fd: no message header
> process_mux_new_session: failed to receive fd 0 from slave
> mux_client_request_session: read from master failed: Connection reset by peer
> Failed to connect to new control master
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> ERROR: RuntimeError: Failed to launch command ["rsync", "-rL", "--rsh=ssh root@...ControlMaster=auto -o ControlPath=... -o ControlPersist=3600", "--delete-after", "-zt"...

After some research it seems that ssh ControlMaster is still broken in cygwin: http://www.cygwin.com/ml/cygwin/2015-01/msg00123.html

<del>So I manually went to solo_cook.rb and took out the ssh_command part from cmd in the rsync block: so it becomes: `cmd = ['rsync', '-rL', rsync_debug, rsync_permissions]`</del>

UPDATE: After following the source code carefully this time, I found that it could be turned off by `--ssh-control-master=no` when running `knife solo cook`. But this probably should be turned off by default for windows hosts for now.

**Comment by matschaffer** [comment]
Ouch. Well this is probably enough reason to remove it. I've been thinking we may be better off staging everything to a local dir then rsyncing in one shot. It should get most of the same speed gain without this sort of oddity.

In the mean time a PR to skip the control socket stuff for cygwin would certainly be appreciated.

**Comment by davidski** [comment]
Thanks to @xunnanxu for the report. As a new knife on windows user, this had been driving me crazy. the `--ssh-control-master=no` seems to be working for me.

**Comment by xunnanxu** [comment]
I believe I already fixed this long time ago (or this is already superseded in newer version per @matschaffer 's long term plan) so closing this.

**Comment by matschaffer** [comment]
Thanks for the followup @xunnanxu and thanks for the fix! https://github.com/matschaffer/knife-solo/pull/453
