### ISSUE TITLE
knife solo cook rsync error

### ISSUE THREAD

**Issue by dale11** [matschaffer/knife-solo#469]
OS:redhat 6.6

[chef@chefServer chef-repo]$ knife solo cook chef@192.168.10.204 ./nodes/node1.json
Running Chef on 192.168.10.204...
Checking Chef version...
Uploading the kitchen...
^C[chef@chefServer chef-repo]$ rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(546) [sender=3.0.6]

**Comment by matschaffer** [comment]
Could use some more detail here. Looks like you canceled the operation, but no info as to why. Also running with `-VV` will provide debug output which may help too.

**Comment by dale11** [comment]
1.Install the following software into the RedHat 6.6.
**************************************************
ruby 2.1.5
knife-solo-0.5.1.gem
**************************************************
2.Run command again with "-W",
but "Uploading the kitchen..." is waiting long time,
the OS is not response.
I have to cancel the operation.
**************************************************
[chef@study chef-repo]$ knife solo cook chef@192.168.10.204 ./nodes/node1.json -W
DL is deprecated, please use Fiddle
Running Chef on 192.168.10.204...
Checking Chef version...
Uploading the kitchen...
^C[chef@study chef-repo]$ rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(546) [sender=3.0.6]

[chef@study chef-repo]$
**************************************************
3.Survey results:
when the following file exist,
Command "knife solo cook" is success.
when the following file not exist,
Command "knife solo cook" is failure,rsync error.
**************************************************
srw-------. 1 chef chef 0  1月 14 19:35 2016 /home/chef/.chef/knife-solo-sockets/192.168.10.204
**************************************************

4.replace "knife-solo-0.5.1.gem" to "knife-solo-0.4.2.gem"
No problem at all

**Comment by matschaffer** [comment]
Likely an issue with the control sockets then.

You can stick to 0.4.2 or maybe try specifying `--ssh-control-master no` if you want to still use 0.5.1.

**Comment by dale11** [comment]
Tanks for your answer!

**Comment by matschaffer** [comment]
Any time! :)
