### ISSUE TITLE
knife solo prepare fails on AWS CentOS 7 AMI

### ISSUE THREAD

**Issue by plentz** [matschaffer/knife-solo#472]
I think that this should just be ignored, but since its a warning, knife fails to run.

```
Bootstrapping Chef...
ERROR: SyntaxError: (eval):1: syntax error, unexpected tSYMBEG, expecting end-of-input
...straps::/etc/profile.d/lang.sh:line19:warning:setlocale:LC_C...
...
```

The original message probably is `/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory`. To fix this all you need to do is add the folllowing to `/etc/environment`:

```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

related:
- http://keiwt.hatenablog.com/entry/2014/10/31/231157

**Comment by artursmolarek** [comment]
I noticed the same problem on RHEL 6.x/7.x (AWS). Your workaround works. Thanks.

**Comment by plentz** [comment]
I think this is solved @ v0.7.0.pre

**Comment by plentz** [comment]
My bad. I think that what changed is that the newer CentOS AMI comes with those settings in place.

**Comment by matschaffer** [comment]
Well, that works too. Thanks @plentz
