### ISSUE TITLE
Impossible to use on Windows

### ISSUE THREAD

**Issue by rthideaway** [matschaffer/knife-solo#477]
It's impossible to use "knife solo" on Windows machine basides regular "knife" command since it is always evaluated just as "knife" and you'll get just knife's help:

```
C:\Ruby22-x64\DevKit>knife solo
FATAL: Cannot find subcommand for: 'solo'
Available subcommands: (for details, knife SUB-COMMAND --help)

** BOOTSTRAP COMMANDS **
knife bootstrap FQDN (options)
knife bootstrap windows ssh FQDN (options)
knife bootstrap windows winrm FQDN (options)
...
```

Knife-solo gem is installed for sure:

```
C:\Ruby22-x64\DevKit>gem query --local | grep knife-solo
knife-solo (0.5.1)
```

Is there any workaround around this issue? I am force to use Windows machine for a while and I can't live without "knife solo" anymore :/

**Comment by matschaffer** [comment]
I suspect the knife you're calling isn't in the same gemset as knife solo is. If knife is coming from chefdk you'll need to install knife-solo using `chef gem install` instead of just `gem install`.

**Comment by rthideaway** [comment]
You are totally right, it's exactly like this. Knife solo was installed via regular Ruby instance (not the one embedded with chef), but it use to work on my Ubuntu this way. I somehow always installed gems from regular Ruby and left the Chef embedded gems untouched. On Windows probably Ruby gems just don't have that higher priority when command gets executed and it ends up calling knife from Chef. Nevermind, I can install knife solo with chef gem of course and thus closing this.!

**Comment by matschaffer** [comment]
Lovely! Just watch out for #478 if you're also using berkshelf & chefdk.

**Comment by rthideaway** [comment]
Watching already like probably many of us. Currently using chefdk 0.9.0 as a workaround...

**Comment by matschaffer** [comment]
Thankfully for knife solo the integration is fairly light.

The nastiest part will probably be parsing the version output so we can use
'install --path' or 'vendor' for backward compatibility.

On Monday, 8 February 2016, rthideaway <notifications@github.com> wrote:

> Watching already like probably many of us. Currently using chefdk 0.9.0 as
> a workaround...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/477#issuecomment-181368110>
> .
>


-- 

-Mat

matschaffer.com
