### ISSUE TITLE
Compatibility with berkshelf from chefdk 0.10.0

### ISSUE THREAD

**Issue by matschaffer** [matschaffer/knife-solo#478]
As originally reported in #476, attempting use knife-solo with chefdk 0.10.0 leads to an error because the versions of httpclient required by berkshelf and knife are not compatible with each other.

See https://github.com/chef/chef-dk/issues/603 for details on the incompatibility.

Baring any updates from chef, the fix should be to shell out to `berks vendor` and parsing any output/return appropriately.

See https://gist.github.com/matschaffer/b386abcc1d88863dcc5a for a vagrant example that demonstrates how the flow _should_ work, but doesn't if 0.10.0 is used.

## Current workarounds
* Use chefdk 0.9.0
* Use ruby & bundler directly to lock compatible httpclient versions

**Comment by drazzib** [comment]
As a side note, I've upgraded my Chef DK to lastest release 0.11.0 and got the following error **Unable to activate knife-solo-0.5.1, because net-ssh-3.0.2 conflicts with net-ssh (< 3.0, ~> 2.7)**

Full stacktrace :
```
$> knife solo prepare host1.example.com
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate knife-solo-0.5.1, because net-ssh-3.0.2 conflicts with net-ssh (< 3.0, ~> 2.7) (Gem::ConflictError)
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1408:in `activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:196:in `rescue in try_activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:in `try_activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /home/XXX/.chefdk/gem/ruby/2.1.0/gems/knife-solo-0.5.1/lib/chef/knife/solo_bootstrap.rb:2:in `<top (required)>'

```

**Comment by boblannon-picwell** [comment]
:+1: same issue in chef-dk 0.11.0, installed via `brew cask install`

**Comment by lbdremy** [comment]
If net-ssh dependency is upgraded to 3.0.2 would it solve the issue ? Apparently only one breaking change https://github.com/net-ssh/net-ssh/blob/master/CHANGES.txt.

**Comment by matschaffer** [comment]
@lbdremy that would likely solve the issue @drazzib posted, but I don't believe it will have any impact on this issue (originally reported in #476).

**Comment by nickbroon** [comment]
+1 for the net-ssh problem mentioned.
Should I open a new issue just for that?

**Comment by trinitronx** [comment]
With ChefDK `0.11.2-1` + `knife-solo-0.5.1` installed via: `brew cask install chefdk; chef exec gem install knife-solo`:


```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate knife-solo-0.5.1, because net-ssh-3.0.2 conflicts with net-ssh (< 3.0, ~> 2.7) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1408:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:196:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/jcuzella/.chefdk/gem/ruby/2.1.0/gems/knife-solo-0.5.1/lib/chef/knife/cook.rb:1:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:104:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:118:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:148:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:209:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:50:in `load'
	from /usr/local/bin/knife:50:in `<main>'
```

**Comment by swettk** [comment]
:+1:

**Comment by awaltman** [comment]
Another +1 to please fix the net-ssh dependency.

**Comment by tal5ab** [comment]
anyone know what steps i need to do to downgrade to 0.9.0 ?
Or is there an easier workaround ?

**Comment by matschaffer** [comment]
Should be able to rm /opt/chefdk and reinstall an earlier version.

On Sunday, 20 March 2016, Tal Abramson <notifications@github.com> wrote:

> anyone know what steps i need to do to downgrade to 0.9.0 ?
> Or is there an easier workaround ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/478#issuecomment-198908390>
>


-- 

-Mat

matschaffer.com

**Comment by tal5ab** [comment]
I am on windows server
i uninstalled chefDK and reinstall version 9.0.0
But still getting same error:
```

C:\QAOps\test1>knife solo cook root@xxxx --ssh-control-master=no
Running Chef on xxxx...
Checking Chef version...
root@xxxx's password:
root@xxxx's password:
Uploading the kitchen...
ERROR: RuntimeError: Failed to launch command ["rsync", "-rL", "--chmod=ugo=rwX"
, "--rsh=ssh root@xxxx", "--delete-after", "-zt", "--exclude=revision
-deploys", "--exclude=.git", "--exclude=.hg", "--exclude=.svn", "--exclude=.bzr"
, "/cygwin64/C/Users/yyy/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife
-solo-0.5.1/lib/knife-solo/resources/patch_cookbooks/", ":~/chef-solo/cookbooks-
1"]

C:\QAOps\test1>chef --version
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```

**Comment by matschaffer** [comment]
Nice work! For any future readers note that the above error is not a chefdk-related problem.

**Comment by boris** [comment]
The only workaround is installing 0.9.0? What about earlier version != 0.12.x? (BTW, I got this behaviour with 0.12.0)

**Comment by matschaffer** [comment]
Pretty sure the incompatibility starts with chefdk 0.10. But if you find
otherwise please report back.

On Monday, 28 March 2016, Boris Quiroz <notifications@github.com> wrote:

> The only workaround is installing 0.9.0? What about earlier version !=
> 0.12.x? (BTW, I got this behaviour with 0.12.0)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/478#issuecomment-202177117>
>


-- 

-Mat

matschaffer.com

**Comment by boris** [comment]
Just tested chefDK 0.10.0, 0.11.0, 0.11.2 and 0.12.0 on Mac OS X 10.11, and none of them are working. 0.9.0 does the trick.

**Comment by matschaffer** [comment]
Thanks Boris! I definitely appreciate the testing help.

On Wednesday, 30 March 2016, Boris Quiroz <notifications@github.com> wrote:

> Just tested chefDK 0.10.0, 0.11.0, 0.11.2 and 0.12.0 on Mac OS X 10.11,
> and none of them are working. 0.9.0 does the trick.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/478#issuecomment-203153337>
>


-- 

-Mat

matschaffer.com

**Comment by jslusher** [comment]
+1 to get this fixed. I would help if I could.

**Comment by jeroenj** [comment]
I've loosened the dependency in #481. This makes knife-solo work again on chefdk v0.10.0+.

The berkshelf issue should also be fixed in chefdk v0.12.0 as they've updated berkshelf to depend on the same version of httpclient as knife.

**Comment by rmoriz** [comment]
may we have a release for this fix?

**Comment by matschaffer** [comment]
See #485 for progress on the release.

On Thursday, 7 April 2016, Roland Moriz <notifications@github.com> wrote:

> may we have a release for this fix?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/478#issuecomment-206789205>
>


-- 

-Mat

matschaffer.com
