### ISSUE TITLE
some hosts return corrupted mac detected error

### ISSUE THREAD

**Issue by tal5ab** [matschaffer/knife-solo#487]
after setting up ssh key authentication between my windows server and the unix hosts
some of them return this error when executing cook:
C:\Server\Kitchen_root>knife solo cook root@HOST -i C:\cygwin64\home\user\.ssh\id_rsa  --ssh-control-master
no -j  '{"user" : "usr" ,"home" : "/export/home/usr" ,"group" : "dba" ,"host" : "HOST" }' -r "install_GA
_PG::install"
Running Chef on HOST...
Checking Chef version...
ERROR: Net::SSH::Exception: corrupted mac detected

Google point this can be a bug in NET::SSH
So i am pretty sure this is not a knife-solo bug

I am trying to find what is different between the hosts 
I can use some direction on possible libraries to check etc

**Comment by matschaffer** [comment]
I'd probably debug by writing directly against Net::SSH and trying to reproduce it. 

The best bugs are ones with reproducible scripts so I'm sure you'll make some headway once you have that. 

The code in https://github.com/matschaffer/knife-solo/blob/master/lib/knife-solo/ssh_connection.rb should help.
