### ISSUE TITLE
break with ChefDK 0.13.21

### ISSUE THREAD

**Issue by chrisduong** [matschaffer/knife-solo#488]
Hi,

I'm using the ChefDK version **0.13.21**, I installed this gem with `chef gem install knife-solo`, and then I bumped to this issue.

> /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate knife-solo-0.5.1, because net-ssh-3.1.1 conflicts with net-ssh (< 3.0, ~> 2.7) (Gem::ConflictError)
>     from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1408:in`activate'
>     from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:200:in `rescue in try_activate'
>     from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:in`try_activate'
>     from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
>     from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in`require'
>     from /Users/cduong/.chefdk/gem/ruby/2.1.0/gems/knife-solo-0.5.1/lib/chef/knife/cook.rb:1:in `<top (required)>'
>     from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb:100:in`load'
>     from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb:100:in `block in load_commands'
>     from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb:100:in`each'
>     from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb:100:in `load_commands'
>     from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb:110:in`load_command'
>     from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb:124:in `command_class_from'
>     from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife.rb:153:in`subcommand_class_from'
>     from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife.rb:214:in `run'
>     from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/knife.rb:148:in`run'
>     from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/bin/knife:25:in `<top (required)>'
>     from /opt/chefdk/bin/knife:51:in`load'

Even though I have  gem net-ssh with 2 versions `(3.1.1, 2.9.4)`, but knife is still using the later one. I don't know how to force the **2.9.4** for ChefDK gem set.

> chef gem list | grep ssh
> net-ssh (3.1.1, 2.9.4)
> net-ssh-gateway (1.2.0)
> net-ssh-multi (1.2.1)

**Comment by matschaffer** [comment]
The next release should fix this.

I've been struggling to get the integration suite updated and green for the
release though.

In the mean time downgrading chefdk or using knife-solo master are the
recommended workarounds.

On Friday, 20 May 2016, chrisd <notifications@github.com> wrote:

> Hi,
>
> I'm using the ChefDK version *0.13.21*, I installed this gem with chef
> gem install knife-solo, and then I bumped to this issue.
>
> /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2288:in
> raise_if_conflicts': Unable to activate knife-solo-0.5.1, because
> net-ssh-3.1.1 conflicts with net-ssh (< 3.0, ~> 2.7) (Gem::ConflictError)
> from
> /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1408:in
> activate'
> from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:200:in rescue
> in try_activate'
> from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:in
> try_activate'
> from
> /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in
> rescue in require'
> from
> /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in
> require'
> from
> /Users/cduong/.chefdk/gem/ruby/2.1.0/gems/knife-solo-0.5.1/lib/chef/knife/cook.rb:1:in
> <top (required)>'
> from
> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb:100:in
> load'
> from
> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb
> 💯in block in load_commands'
> from
> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb:100:in
> each'
> from
> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb
> 💯in load_commands'
> from
> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb:110:in
> load_command'
> from
> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/core/subcommand_loader.rb:124:in
> command_class_from'
> from
> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife.rb:153:in
> subcommand_class_from'
> from
> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife.rb:214:in
> run'
> from
> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/knife.rb:148:in
> run'
> from
> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/bin/knife:25:in <top
> (required)>'
> from /opt/chefdk/bin/knife:51:inload'
>
> Even though I have gem net-ssh with 2 versions (3.1.1, 2.9.4), but knife
> is still using the later one. I don't know how to force the *2.9.4* for
> ChefDK gem set.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/matschaffer/knife-solo/issues/488>
>


-- 

-Mat

matschaffer.com

**Comment by git-ong** [comment]
Installing knife-solo 0.7.0pre works for me:
```
chef gem install knife-solo -v "0.7.0pre"
```

**Comment by matschaffer** [comment]
Thanks for reporting @git-ong - still need to get a proper release out but I'll close this ticket for now.
