### ISSUE TITLE
knife-solo, net-ssh, and ed25519

### ISSUE THREAD

**Issue by chapmajs** [matschaffer/knife-solo#511]
I'm currently running off of `master` due to needing `ed25519` key support, which requires `net-ssh ~> 4.0.0`. Just wondering when `0.7.0` is looking like it might be released. I prefer not to run off of `master` for production environments, especially since we have to prefix everything with `bundle exec` now, to get `knife solo` picked up (didn't install with binstubs for whatever reason).

**Comment by matschaffer** [comment]
I year you @chapmajs - definitely in need of a release here I just haven't had the time to check the integration suite.

If you'd be interested in helping out let me know.
