### ISSUE TITLE
I wonder how the version of chef, that knife solo prepare installs on the target, is chosen.

### ISSUE THREAD

**Issue by janskarvall** [matschaffer/knife-solo#532]
I am trying to cook an Ubuntu 18.04 target, and got stuck on the [Remove update-rc.d -n (dryrun) option. #6723](https://github.com/chef/chef/pull/6723) bug.

From what I understand, that bug is fixed in chef 14.0.8, and there is even an 14.1.12 Chef Client available at [Chef downloads](https://downloads.chef.io/).

The chef version that `knife solo prepare` installs on the target is 13.8.5-1. I am using chefdk 2.5.3-1.

Actually, I am also uncertain if the chef binary that knife-solo installs is the Chef Client.

**Comment by matschaffer** [comment]
Ubuntu should get picked up by [this match](https://github.com/matschaffer/knife-solo/blob/master/lib/knife-solo/bootstraps/linux.rb#L81-L82) which uses https://github.com/matschaffer/knife-solo/blob/master/lib/knife-solo/bootstraps/linux.rb#L53-L56 and https://github.com/matschaffer/knife-solo/blob/master/lib/knife-solo/bootstraps.rb#L76-L83 the `-v` arg comes in via the `--bootstrap-version` parameter or config variable as seen in https://github.com/matschaffer/knife-solo/blob/master/lib/chef/knife/solo_prepare.rb#L21-L24

**Comment by matschaffer** [comment]
Hope that helps, feel free to reopen if you think I've missed something.
