### ISSUE TITLE
Chef not installing in google cloud server

### ISSUE THREAD

**Issue by ramachandranv** [matschaffer/knife-solo#537]
I'm running the following prepare statement in one of our google cloud server. But it's not downloading or install chef and just breaks creating a node file.

knife solo prepare -i ~/.ssh/id_rsa.pub ramachandran@35.246.78.52                                                                                                  
Bootstrapping Chef...
Updating apt caches...
Installing required packages...
Installing rubygems from source...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  243k  100  243k    0     0  5388k      0 --:--:-- --:--:-- --:--:-- 5418k

**Comment by matschaffer** [comment]
Debug output would be good. Pretty sure it's `-l debug`

**Comment by ramachandranv** [comment]
@matschaffer  -l debug doesn't work

**Comment by matschaffer** [comment]
Ah, whoops. Looks like it's `-VV` https://docs.chef.io/knife_options.html

**Comment by ramachandranv** [comment]
@matschaffer Thank you. There is some issue with the server it seems. I tried setting up with creating new servers and it does work well.
